# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'PoolLocalWindows'

steps:
- checkout: self

- script: npm install
  displayName: 'Installer les dépendances'

- script: npm test
  displayName: 'Lancer les tests'

- task: AzureCLI@2
  displayName: 'Déployer sur App Service'
  inputs:
    azureSubscription: 'SC_EXAM-AZURE'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      inlineScript: |
      cd $(Build.SourcesDirectory)
      Compress-Archive -Path server.js, package.json, index.html -DestinationPath app.zip -Force
      az webapp deploy --resource-group rg-tp-azure-exam --name backend-tp-azure-vts --src-path app.zip --type zip