trigger:
- main

pool:
  name: 'PoolLocalWindows'

steps:
- checkout: self

- script: npm install
  displayName: 'Installer les dépendances'

- script: npm test
  displayName: 'Lancer les tests'

- task: AzureCLI@2
  displayName: 'Deployer sur App Service'
  inputs:
    azureSubscription: 'SC_EXAM-AZURE'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp up --name backend-tp-azure-vts --resource-group rg-tp-azure-exam --runtime "NODE:20-lts"